language: node_js
node_js:
    - node
    - lts/*
    - 14.13.0
script: npm test

jobs:
    include:
        - stage: npm release
          if: fork = false AND tag =~ /^v\d+(\.\d+){2}$/
          script: skip
          deploy:
              provider: npm
              email: npm@totally.rip
              on:
                  tags: true
              api_token:
                  secure: "2The2UsnN3F55QDLfYTOP9/EGiARRdu7KnmGRNtAmM8j99sO11d2YyifwQomEH4yf2BI+NQ3gJgzPb+YNjc3jBUv3Z6z/mtL326aCH8lfD+9d5CFCh9MUJpg4egS8pAU0kMoRRhVCVdemhucMacN2y4vfZvudgxf4l3aZo07yq4pKewaVR4iLdEBtIg28UAL5ihAnPDPXBnksJlync8KpCH/GPHHYo/3mABiWvfbB1G9yyJeWdWSqLbyJWmP5i2jgYrzM/Rv1FlUizBisTzSv3bOJyFh0jbzgm/I0Of5Cco1J6yZqovbpoKcJEdXqQpY1wQlwuZ0tRJde/cAiauaJDxXiaEsSxGJysgA40iuL0emVo15cUkf3h3PsHs3vuxjvlNNI+KY7PI8pat8Jc5VubcTcRxRuAnU8pC4v4212e+sosEoqEUmoMk6IBXtNWZgGPugsE66SeJOZZFvVKezllz3v7ZuyqkhJ3Vh6yrSHpVFYnEra5uZRadbT/5nWblSnyDlZBYozRcgltnmic1zN7Ac5A9SaWonhfBf+/M9pjCP/VGwf33IrQueykACW1GjS3adVWlsl5jQr8rzuA3MyDV2WiEztA06jAD1xEpLVgLCa9fmYQI4PZY9XGytBpjJPWT8Mi9t/E4RLFVKJ1GBmPaZD6ejTpvYYLCJmBYCqI0="
